In [0]:
from zipfile import ZipFile
file_name="aliza2.zip"
with ZipFile(file_name,'r') as zip:
  zip.extractall()
  print(done)



In [0]:
from google.colab import files

with open('mode1.cnn', 'w') as f:
  f.write('model1.hdf5')

files.download('model1.cnn')

----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46630, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/lib/python3.6/http/server.py", line 639, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.6/http/server.py", line 800, in copyfile
    shutil.copyfil

In [0]:
from google.colab import files

with open('example.txt', 'w') as f:
  f.write('some content')

files.download('example.txt')

In [0]:
!wget -O aliza2.zip https://doc-0k-90-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/9393n4l4tac48a19ktid5a0a2q5jpfrs/1580090400000/09750456226342476441/*/15otGqHvpdUgwGVs_hJKqnQ3U3LrVcaE0?e=download

--2020-01-27 04:47:38--  https://doc-0k-90-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/9393n4l4tac48a19ktid5a0a2q5jpfrs/1580090400000/09750456226342476441/*/15otGqHvpdUgwGVs_hJKqnQ3U3LrVcaE0?e=download
Resolving doc-0k-90-docs.googleusercontent.com (doc-0k-90-docs.googleusercontent.com)... 108.177.125.132, 2404:6800:4008:c01::84
Connecting to doc-0k-90-docs.googleusercontent.com (doc-0k-90-docs.googleusercontent.com)|108.177.125.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘aliza2.zip’

aliza2.zip              [             <=>    ] 665.39M   276MB/s    in 2.4s    

2020-01-27 04:47:46 (276 MB/s) - ‘aliza2.zip’ saved [697712823]



In [0]:
import cv2 as cv
import numpy as np
import os
import matplotlib.pyplot as plt
from tqdm import tqdm
import random

DATADIR="aliza"
CATEGORIES=["ten","twenty","fifty"]
img_size=256


In [2]:

training_data=[]
def create_training_data():
  for i in tqdm(CATEGORIES):
    path=os.path.join(DATADIR,i)
    class_num=CATEGORIES.index(i)
    print(class_num)
    for img in (os.listdir(path)):
      img_array=cv.resize(cv.imread(os.path.join(path,img),cv.IMREAD_COLOR),(img_size,img_size))
      training_data.append([img_array,class_num])
  np.save('train_data.npy',training_data)
  random.shuffle(training_data)       
create_training_data()


  0%|          | 0/3 [00:00<?, ?it/s]

0


 33%|███▎      | 1/3 [00:13<00:26, 13.06s/it]

1


 67%|██████▋   | 2/3 [00:25<00:12, 12.77s/it]

2


100%|██████████| 3/3 [00:39<00:00, 13.30s/it]


In [3]:
X =[]
y =[]
for features,label in training_data:
    X.append(features)
    y.append(label)
X=np.array(X)
y=np.array(y)
print(y)

[1 0 2 ... 0 0 0]


In [4]:
import tensorflow as tf
import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D,BatchNormalization
from tensorflow.keras.callbacks import TensorBoard
from keras.utils import to_categorical  
from tensorflow.python.keras.optimizers import Adam, Adagrad

#NAME="currencyy"
#tensorboard = TensorBoard(log_dir="logs/{}".format(NAME))
X = X.reshape([-1,img_size,img_size, 3])

X=X/255.0
y= to_categorical(y)
print(y)

model = Sequential()

model.add(Conv2D(256,kernel_size=(3, 3),strides=(1,1),input_shape=(img_size,img_size,3)))
#model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256,kernel_size=(3, 3),strides=(1,1)))
#model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))
model.add(Activation('relu'))

model.add(Dense(3))
model.add(Activation('softmax'))
opt=Adam(lr=0.0001)
model.compile(loss='categorical_crossentropy',optimizer=opt,metrics=['accuracy'])
#model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])#binary for using only two classes
#model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])#binary for using only two classes

model.fit(X, y, batch_size=32, epochs=4, validation_split=0.2)
model.save('model1.hdf5')


Using TensorFlow backend.


[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Train on 4934 samples, validate on 1234 samples
Epoch 1/4
4934/4934 [==============================] - 47s 10ms/sample - loss: 0.6079 - acc: 0.7268 - val_loss: 0.4258 - val_acc: 0.8379
Epoch 2/4
4934/4934 [==============================] - 39s 8ms/sample - loss: 0.2810 - acc: 0.8950 - val_loss: 0.2203 - val_acc: 0.9092
Epoch 3/4
4934/4934 [==============================] - 39s 8ms/sample - loss: 0.1362 - acc: 0.9601 - val_loss: 0.1968 - val_acc: 0.9190
Epoch 4/4
4934/4934 [==============================] - 39s 8ms/sample - loss: 0.0762 - acc: 0.9805 - val_loss: 0.1281 - val_acc: 0.9562


In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 254, 254, 256)     7168      
_________________________________________________________________
activation (Activation)      (None, 254, 254, 256)     0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 127, 127, 256)     0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 125, 125, 256)     590080    
_________________________________________________________________
activation_1 (Activation)    (None, 125, 125, 256)     0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 62, 62, 256)       0         
_________________________________________________________________
flatten (Flatten)            (None, 984064)            0

In [7]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import TensorBoard

model = tf.keras.models.load_model("model1.hdf5")

prediction = model.predict(prepare('a1.jpg'))
print(prediction)


[[1. 0. 0.]]


In [0]:
def prepare(filepath):
    img_array = cv.imread(filepath, cv.IMREAD_COLOR)  # read in the image, convert to grayscale
    new_array = cv.resize(img_array, (img_size,img_size))# resize image to match model's expected sizing
    new_array=new_array/1.0
    return new_array.reshape(-1,img_size,img_size, 3)  # return the image with shaping that TF wants.
